core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

from accounts.views import AccountLoginView
from sales.views import (
    SalesOrderListAPIView,
    SalesOrderCreateAPIView,
    SalesOrderUpdateAPIView,
    SalesOrderDestroyAPIView,
)

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api/sales_orders/list/', SalesOrderListAPIView.as_view(), name='sales_order_list_api'),
    path('api/sales_orders/create/', SalesOrderCreateAPIView.as_view(), name='sales_order_create_api'),
    path('api/sales_orders/update/', SalesOrderUpdateAPIView.as_view(), name='sales_order_update_api'),
    path('api/sales_orders/destroy/', SalesOrderDestroyAPIView.as_view(), name='sales_order_destroy_api'),
    path('api/token/', obtain_auth_token, name='obtain-token'),
    path('admin/', admin.site.urls),
    path('', AccountLoginView.as_view()),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('integrations/', include('integrations.urls', namespace='integrations')),
    path('product_studio/', include('product_studio.urls', namespace='product_studio')),
    path('sales/', include('sales.urls', namespace='sales')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path

from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.sales, name='sales'),
    path('faire/', views.faire_api, name='faire'),
]

sales/models.py
from django.db import models


class SalesOrder(models.Model):
    id = models.CharField(primary_key=True, max_length=100, verbose_name='ID')
    sales_channel = models.CharField(max_length=50, verbose_name='Sales Channel')
    display_id = models.CharField(unique=True, max_length=100, verbose_name='Display ID')
    status = models.CharField(max_length=100, verbose_name='Status')
    source = models.CharField(max_length=100, verbose_name='Source')
    customer = models.CharField(max_length=100, verbose_name='Customer')
    brand_discounts = models.CharField(max_length=100, null=True, blank=True, verbose_name='Brand Discounts')
    original_order_id = models.CharField(max_length=100, null=True, blank=True, verbose_name='Original Order ID')
    created_at = models.DateTimeField(null=True, blank=True, verbose_name='Created At')
    updated_at = models.DateTimeField(null=True, blank=True, verbose_name='Updated At')
    payment_initiated_at = models.DateTimeField(null=True, blank=True, verbose_name='Payment Initiated At')
    processing_at = models.DateTimeField(null=True, blank=True, verbose_name='Processing At')
    expected_ship_date = models.DateField(null=True, blank=True, verbose_name='Expected Ship Date')
    requested_ship_date = models.DateField(null=True, blank=True, verbose_name='Requested_Ship_Date')
    ship_after = models.DateField(null=True, blank=True, verbose_name='Ship After')
    item_subtotal = models.IntegerField(null=True, blank=True, verbose_name='Item Subtotal')
    payout_fee_percentage = models.IntegerField(null=True, blank=True, verbose_name='Payout Fee Percentage')
    payout_fee_cost = models.IntegerField(null=True, blank=True, verbose_name='Payout Fee Cost')
    commission_percentage = models.IntegerField(null=True, blank=True, verbose_name='Commission Percentage')
    commission_cost = models.IntegerField(null=True, blank=True, verbose_name='Commission Cost')
    total_payout = models.IntegerField(null=True, blank=True, verbose_name='Total Payout')

    class Meta:
        verbose_name = 'Sales Order'
        verbose_name_plural = 'Sales Orders'

    def __str__(self):
        return f'{self.display_id} (Total Payout: {self.total_payout})'

sales/forms.py
from django import forms

from .models import SalesOrder


class SalesOrderForm(forms.ModelForm):
    class Meta:
        model = SalesOrder
        fields = (
            'sales_channel',
            'id',
            'display_id',
            'status',
            'source',
            'brand_discounts',
            'original_order_id',
            'created_at',
            'updated_at',
            'payment_initiated_at',
            'processing_at',
            'expected_ship_date',
            'requested_ship_date',
            'ship_after',
            'item_subtotal',
            'payout_fee_percentage',
            'payout_fee_cost',
            'commission_percentage',
            'commission_cost',
            'total_payout',
        )

sales/views.py
from datetime import datetime

from django.shortcuts import render
from rest_framework import generics
from rest_framework import mixins

from .faire import my_faire_store
from .models import SalesOrder
from .serializers import SalesOrderSerializer


def sales(request):
    context = {}

    return render(request, 'sales/sales.html', context)


def faire_api(request):
    faire_orders = my_faire_store()
    db_orders = SalesOrder.objects.all()

    def format_date(faire_datetime):
        date, _ = faire_datetime.split('T')
        date = datetime.strptime(date, '%Y%m%d').date()

        return date

    for order in faire_orders['orders']:
        order['products'] = order['items']
        del order['items']

        order['created_at'] = format_date(order['created_at'])
        order['updated_at'] = format_date(order['updated_at'])

    context = {
        'faire_orders': faire_orders,
        'db_orders': db_orders
    }

    return render(request, 'sales/faire.html', context)


class SalesOrderAPIView(
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    generics.GenericAPIView):

    serializer_class = SalesOrderSerializer
    queryset = SalesOrder.objects.all()

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class SalesOrderListAPIView(generics.ListAPIView):
    serializer_class = SalesOrderSerializer
    queryset = SalesOrder.objects.all()


class SalesOrderCreateAPIView(generics.CreateAPIView):
    serializer_class = SalesOrderSerializer
    queryset = SalesOrder.objects.all()


class SalesOrderUpdateAPIView(generics.UpdateAPIView):
    serializer_class = SalesOrderSerializer
    queryset = SalesOrder.objects.all()


class SalesOrderDestroyAPIView(generics.DestroyAPIView):
    serializer_class = SalesOrderSerializer
    queryset = SalesOrder.objects.all()

sales/templates/sales/faire.html
{% extends "base.html" %}
{% load static %}
{% load mathfilters %}

{% block datatable %}
    <div class="flex flex-col rounded-lg bg-gray-800 w-full h-full overflow-x-auto shadow-2xl">
        <table>
            <thead class="sticky top-0 bg-cyan-600">
                <tr>
                    <th scope="col" class="w-2 rounded-tl-lg"></th>
                    <th scope="col" class="max-w-full px-6 py-3 whitespace-nowrap text-center text-xs font-bold text-black uppercase tracking-wider">Order Status</th>
                    <th scope="col" class="max-w-full px-6 py-3 whitespace-nowrap text-center text-xs font-bold text-black uppercase tracking-wider">Retailer</th>
                    <th scope="col" class="max-w-full px-6 py-3 whitespace-nowrap text-center text-xs font-bold text-black uppercase tracking-wider">Display ID</th>
                    <th scope="col" class="max-w-full px-6 py-3 whitespace-nowrap text-center text-xs font-bold text-black uppercase tracking-wider">Created At</th>
                    <th scope="col" class="max-w-full px-6 py-3 whitespace-nowrap text-center text-xs font-bold text-black uppercase tracking-wider">Updated At</th>
                    <th scope="col" class="max-w-full px-6 py-3 whitespace-nowrap text-center text-xs font-bold text-black uppercase tracking-wider">Quantity</th>
                    <th scope="col" class="max-w-full px-6 py-3 whitespace-nowrap text-center text-xs font-bold text-black uppercase tracking-wider rounded-tr-lg">Order Cost</th>
                </tr>
            </thead>
            <tbody class="bg-gray-800 divide-y divide-black">
                {% for order in db_orders %}
                    <tr class="hover:bg-gray-700">
                        {% if order.status in "DELIVERED" %}
                            <td class="bg-lime-500">
                            </td>
                        {% elif order.status in "PROCESSING" %}
                            <td class="bg-yellow-500">
                            </td>
                        {% elif order.status in "IN_TRANSIT" %}
                            <td class="bg-yellow-500">
                            </td>
                        {% else %}
                            <td class="bg-gray-400">
                            </td>
                        {% endif %}
                        <td class="whitespace-nowrap text-lowercase font-normal">
                            <div class="p-3 text-xs text-white">
                                {{ order.status }}
                            </div>
                        </td>
                        <td class="whitespace-nowrap font-bold">
                            <div class="p-3 text-xs text-white">
                                {{ order.customer }}
                            </div>
                        </td>
                        <td class="whitespace-nowrap text-center font-normal">
                            <div class="p-3 text-xs text-white">
                                {{ order.display_id }}
                            </div>
                        </td>
                        <td class="whitespace-nowrap text-center font-normal">
                            <div class="p-3 text-xs text-white">
                                {{ order.created_at }}
                            </div>
                        </td>
                        <td class="whitespace-nowrap text-center font-normal">
                            <div class="p-3 text-xs text-white">
                                {{ order.updated_at }}
                            </div>
                        </td>
                        <td class="whitespace-nowrap text-center font-normal">
                            <div class="p-3 text-xs text-white">
                                COMING SOON!
                            </div>
                        </td>
                        <td class="whitespace-nowrap text-center font-normal">
                            <div class="p-3 text-xs text-white">
                                ${{ order.item_subtotal|div:100|floatformat:2 }}
                            </div>
                        </td>
                    </tr>
{#                    <div class="bg-gray-900">#}
{#                        <div class="whitespace-nowrap text-center font-normal">#}
{#                            <div class="p-3 text-xs text-white">#}
{#                                Test Row Expansion#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                {% endfor %}
            </tbody>
        </table>
        <div class="py-2 border-t border-black"></div>
    </div>
{% endblock datatable %}

sales/templates/sales/sales.html
{% extends "base.html" %}

{% block content %}
<div class="flex grid grid-cols-1 gap-4 max-w-64 max-h-32 bg-gray-900">
    <div class="flex flex-col justify-start p-2 h-32 rounded-lg shadow-2xl text-white uppercase tracking-wider">
        Sales Channels
    <div class="bg-gray-800 text-sm ml-2 p-2">
        <a href="{% url 'sales:faire' %}">Faire</a>
    </div>
    </div>
</div>
{% endblock content %}