accounts/urls.py
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path

from .views import (
    AccountCreateView,
    AccountDeleteView,
    AccountDetailView,
    AccountListView,
    AccountUpdateView,
    AccountLoginView,
    AccountLogoutView,
)

urlpatterns = [
    path('', AccountListView.as_view(), name='account-list'),
    path('create/', AccountCreateView.as_view(), name='account-create'),
    path('<int:account_id>/', AccountDetailView.as_view(), name='account-detail'),
    path('<int:account_id>/update/', AccountUpdateView.as_view(), name='account-update'),
    path('<int:account_id>/delete/', AccountDeleteView.as_view(), name='account-delete'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

from accounts.views import AccountLoginView
from sales.views import (
    SalesOrderListAPIView,
    SalesOrderCreateAPIView,
    SalesOrderUpdateAPIView,
    SalesOrderDestroyAPIView,
)

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api/sales_orders/list/', SalesOrderListAPIView.as_view(), name='sales_order_list_api'),
    path('api/sales_orders/create/', SalesOrderCreateAPIView.as_view(), name='sales_order_create_api'),
    path('api/sales_orders/update/', SalesOrderUpdateAPIView.as_view(), name='sales_order_update_api'),
    path('api/sales_orders/destroy/', SalesOrderDestroyAPIView.as_view(), name='sales_order_destroy_api'),
    path('api/token/', obtain_auth_token, name='obtain-token'),
    path('admin/', admin.site.urls),
    path('', AccountLoginView.as_view()),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('integrations/', include('integrations.urls', namespace='integrations')),
    path('product_studio/', include('product_studio.urls', namespace='product_studio')),
    path('sales/', include('sales.urls', namespace='sales')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_studio/urls.py
from django.urls import path

from . import views

app_name = 'product_studio'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_studio'),
    path('create/', views.ProductCreateView.as_view(), name='product_create'),
    path('smart_reorder/', views.ProductPartSmartReorder.as_view(), name='smart_reorder'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
{#<html {% if user.settings.dark_mode %}class="dark"{% endif %}>#}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Testrix - A JTBD Manager</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body class="h-screen overflow-hidden bg-primary-900 flex flex-col">
        {% if user.is_authenticated %}
            {% include 'navbar-top.html' %}
        {% endif %}
        <div class="min-h-0 flex-1 flex overflow-hidden">
            {% if user.is_authenticated %}
                {% include 'navbar-side.html' %}
            {% endif %}
            <main class="min-w-0 flex-1 bg-primary-100 lg:flex rounded-2xl p-4">
                <section aria-labelledby="primary-heading" class="min-w-0 flex-1 h-full flex flex-col overflow-hidden lg:order-last">
                    {% block content %}
                    {% endblock content %}
                </section>
            </main>
        </div>
    </body>
</html>

templates/navbar-side.html
{% load static %}

<div class="flex flex-col w-20">
    <div class="flex flex-col h-0 flex-1 overflow-y-auto bg-primary-900">
        <div class="flex-1 flex flex-col">
            <div class="flex-shrink-0 py-4 flex items-center justify-center rounded-b-xl border-b-4 border-primary-100">
                <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark.svg?color=white" alt="Workflow">
            </div>
            <nav aria-label="Sidebar" class="py-6 flex flex-col items-center space-y-3">
                <a href="#" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/dashboard/' in request.path %}bg-primary-700{% endif %}">
                    {% include 'icons/heroicons/outline/template-icon.html' %}
                    <span class="sr-only">Dashboard</span>
                </a>
                <a href="{% url 'product_studio:product_studio' %}" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/product_studio/' in request.path %}bg-primary-700{% endif %}">
                    {% include 'icons/heroicons/outline/collection-icon.html' %}
                    <span class="sr-only">Projects</span>
                </a>
                <a href="#" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/teams/' in request.path %}bg-primary-700{% endif %}">
                    {% include 'icons/heroicons/outline/user-group-icon.html' %}
                    <span class="sr-only">Teams</span>
                </a>
                {% if user.is_superuser %}
                    <a href="{% url 'accounts:account-list' %}" class="flex items-center p-4 rounded-lg text-white hover:bg-primary-700 {% if '/accounts/' in request.path %}bg-primary-700{% endif %}">
                        {% include 'icons/heroicons/outline/users-icon.html' %}
                        <span class="sr-only">Users</span>
                    </a>
                {% endif %}
            </nav>
        </div>
        <div class="flex-shrink-0 py-4 flex items-center justify-center rounded-t-xl">
            <a href="#" class="flex-shrink-0 w-full">
                <img class="block mx-auto h-10 w-10 rounded-full" src="{{ user.profile_picture.url }}" alt="">
                <div class="sr-only">
                    <p>
                        {{ user.get_full_name }}
                    </p>
                    <p>
                        Account settings
                    </p>
                </div>
            </a>
        </div>
    </div>
</div>

templates/navbar-top.html
{% load static %}

<nav class="bg-primary-900">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
                <div class="hidden md:block">
                    <div class="ml-10 flex items-baseline space-x-4">

                        <a href="#" class="text-primary-300 hover:bg-primary-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Dashboard</a>

                        <a href="#" class="text-primary-300 hover:bg-primary-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Team</a>

                        <a href="#" class="text-primary-300 hover:bg-primary-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Projects</a>

                        <a href="#" class="text-primary-300 hover:bg-primary-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Calendar</a>

                        <a href="#" class="text-primary-300 hover:bg-primary-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Reports</a>
                    </div>
                </div>
            </div>
            <div class="hidden md:block">
                <div class="ml-4 flex items-center md:ml-6">
                    <button class="bg-primary-800 p-1 rounded-full text-primary-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-primary-800 focus:ring-white">
                        <span class="sr-only">View notifications</span>
                        <!-- Heroicon name: outline/bell -->
                        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                        </svg>
                    </button>

                    <!-- Profile dropdown -->
                    <div class="ml-3 relative">
                        <div>
                            <button type="button" class="max-w-xs bg-primary-800 rounded-full flex items-center text-sm text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-primary-800 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                                <span class="sr-only">Open user menu</span>
                                <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                            </button>
                        </div>

                        <!--
                            Dropdown menu, show/hide based on menu state.

                            Entering: "transition ease-out duration-100"
                                From: "transform opacity-0 scale-95"
                                To: "transform opacity-100 scale-100"
                            Leaving: "transition ease-in duration-75"
                                From: "transform opacity-100 scale-100"
                                To: "transform opacity-0 scale-95"
                        -->

                        <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                            <!-- Active: "bg-primary-100", Not Active: "" -->
                            <a href="#" class="block px-4 py-2 text-sm text-primary-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>

                            <a href="#" class="block px-4 py-2 text-sm text-primary-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>

                            <a href="#" class="block px-4 py-2 text-sm text-primary-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>